<?php

namespace App\Filament\Pages;

use App\Filament\Resources\EventResource\Widgets\EventsGoing;
use app\Filament\Resources\EventResource\Widgets\EventsHosting;
use App\Filament\Resources\EventResource\Widgets\StatsOverview;
use Filament\Pages\Dashboard;

class DashboardEvents extends Dashboard
{
    protected static ?string $navigationIcon = 'heroicon-o-home';

    protected function getHeaderWidgets(): array
    {
        return [
//            EventsHosting::class,
            EventsGoing::class,
//            StatsOverview::class
        ]; // TODO: Change the autogenerated stub
    }
}
